export const PRODUCT_CONFIG = {
  PARTICIPANT_COUNT: 9,
  ENTRY_FEE_BRL: 100,
  PRIZE_PERCENTAGES: { first: 0.70, second: 0.20, third: 0.10 },
} as const

export const TOTAL_PRIZE_BRL = PRODUCT_CONFIG.PARTICIPANT_COUNT * PRODUCT_CONFIG.ENTRY_FEE_BRL
export const PRIZE_FIRST_BRL = TOTAL_PRIZE_BRL * PRODUCT_CONFIG.PRIZE_PERCENTAGES.first
export const PRIZE_SECOND_BRL = TOTAL_PRIZE_BRL * PRODUCT_CONFIG.PRIZE_PERCENTAGES.second
export const PRIZE_THIRD_BRL = TOTAL_PRIZE_BRL * PRODUCT_CONFIG.PRIZE_PERCENTAGES.third
